#!/bin/bash

# make: build script for compiling C and Ada with a C entrypoint.
# Copyright (C) 2025-2026, Ada (Tape), <adadispenser@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# # # # # # # # # # # # # # # # # # # # #  CONFIG  # # # # # # # # # # # # # # # # # # # # #

GCCARGS="-Wall -Wextra"
GCCDEBUGARGS="-Wall -Wextra -ggdb3"

GNATARGS=""
GNATDEBUGARGS="--GCC=\"gcc -ggdb3\""

LINKARGS="-lfyaml"

BINNAME="urcltools"

SRCFOLDER="./src"
TEMPFOLDER="./temp"
BUILDFOLDER="./build"

# # # # # # # # # # # # # # # # # # # #  END CONFIG  # # # # # # # # # # # # # # # # # # # #

# iterate throught the source directory recursively, and record any found c files or ada files
scanDir() {
  local dir="${1:-$SRCFOLDER}"   
  dir=$(realpath "$dir")         
  for file in "$dir"/*; do       
    [ -e "$file" ] || continue   
    if [[ -d "$file" ]]; then
      scanDir "$file"
    elif [[ -f "$file" ]]; then
      extension="${file##*.}"
      if [[ "$extension" == "c" ]]; then
        CFILES+=("$file")
      elif [[ "$extension" == "adb" ]]; then
        ADBFILES+=("$file")
      fi
    fi
  done
}

if [ "${1}" == "debug" ]; then
  GCCARGS="${GCCDEBUGARGS}"
  GNATARGS="${GNATDEBUGARGS}"
  BUILDFOLDER="${BUILDFOLDER}/debug"
fi

# clear up temp files
rm -rf "${TEMPFOLDER}"
mkdir "${TEMPFOLDER}"

# get all source files
declare -a CFILES
declare -a ADBFILES

scanDir "${SRCFOLDER}"

echo "${CFILES[@]}"
echo "${ADBFILES[@]}"


# build c files
#gcc -ggdb3 -c main.c
for i in "${CFILES[@]}"
do
  fileName=$(basename ${i})
  fileName="${fileName%.*}"
  gcc ${GCCARGS} -c "${i}" -o "${TEMPFOLDER}/${fileName}.o"
done

# build ada files
#gnatmake --GCC="gcc -ggdb3" -c unit1.adb
adbCount=${#ADBFILES[@]}
if (( adbCount > 0 )); then
  for i in "${ADBFILES[@]}"
  do
    gnatmake ${GCCARGS} -D "${TEMPFOLDER}" -c "${i}"
  done

  # bind .ali files
  finalAli="${ADBFILES[-1]}"
  finalAli=$(basename ${finalAli})
  finalAli="${TEMPFOLDER}/${finalAli%.*}.ali"

  # get array of all .ali files
  declare -a aliFiles
  for i in "${ADBFILES[@]}"
  do
    aliFileName=$(basename ${i})
    aliFile="${TEMPFOLDER}/${aliFileName%.*}.ali"
    aliFiles[${#aliFiles[@]}]="${aliFile}"
  done

  #gnatbind -n unit1.ali unit2.ali
  adbCount=${#ADBFILES[@]}
  if (( adbCount > 0 )); then
    gnatbind -n "${aliFiles[@]}"
  fi
fi

# link into finished output

# get list of .o files generated by gcc
declare -a oFiles
for i in "${CFILES[@]}"
do
  oFileName=$(basename ${i})
  oFile="${TEMPFOLDER}/${oFileName%.*}.o"
  oFiles[${#oFiles[@]}]="${oFile}"
done

#gnatlink unit2.ali main.o -o exec_file
if (( adbCount > 0 )); then
  gnatlink "${finalAli}" "${oFiles[@]}" -o "${BUILDFOLDER}/${BINNAME}" ${LINKARGS}
  
else
  # no ada files, just compile with gcc
  gcc -o "${BUILDFOLDER}/${BINNAME}" "${oFiles[@]}" ${LINKARGS}
fi